// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SyncfusionHelpDesk.Data
{
    public partial class HelpDeskTickets
    {
        public HelpDeskTickets()
        {
            HelpDeskTicketDetails = new HashSet<HelpDeskTicketDetails>();
        }

        public int Id { get; set; }
        public string TicketStatus { get; set; }
        public DateTime TicketDate { get; set; }
        public string TicketDescription { get; set; }
        public string TicketRequesterEmail { get; set; }
        public string TicketGuid { get; set; }

        public virtual ICollection<HelpDeskTicketDetails> HelpDeskTicketDetails { get; set; }
    }
}