// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SyncfusionHelpDesk.Data
{
    public partial class HelpDeskTicketDetails
    {
        public int Id { get; set; }
        public int HelpDeskTicketId { get; set; }
        public DateTime TicketDetailDate { get; set; }
        public string TicketDescription { get; set; }

        public virtual HelpDeskTickets HelpDeskTicket { get; set; }
    }
}