// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncfusionHelpDesk.Models;

public partial class HelpDeskTicketDetail
{
    public int Id { get; set; }

    public int HelpDeskTicketId { get; set; }

    public DateTime TicketDetailDate { get; set; }

    public string TicketDescription { get; set; }

    public virtual HelpDeskTicket HelpDeskTicket { get; set; }
}