// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncfusionHelpDesk.Models;

public partial class HelpDeskTicket
{
    public int Id { get; set; }

    public string TicketStatus { get; set; }

    public DateTime TicketDate { get; set; }

    public string TicketDescription { get; set; }

    public string TicketRequesterEmail { get; set; }

    public string TicketGuid { get; set; }

    public virtual ICollection<HelpDeskTicketDetail> HelpDeskTicketDetails { get; set; } = new List<HelpDeskTicketDetail>();
}